-- Grant access to the AI service.
USE ROLE SECURITYADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_ANALYST_USER
TO ROLE RETAILROCKET_REPORTER;

-- Grant access to our semantic view.
USE ROLE SYSADMIN;

GRANT SELECT, REFERENCES
ON SEMANTIC VIEW RETAILROCKET.ANALYTICS.SV_SESSION_ANALYTICS
TO ROLE RETAILROCKET_REPORTER;

-- Verify using only the reporting role.
USE ROLE RETAILROCKET_REPORTER;
USE SECONDARY ROLES NONE;
USE WAREHOUSE RETAILROCKET_WH;

SELECT CURRENT_ROLE();

SELECT *
FROM SEMANTIC_VIEW(
    RETAILROCKET.ANALYTICS.SV_SESSION_ANALYTICS
    METRICS
        sessions.total_sessions,
        sessions.purchasing_sessions,
        sessions.session_purchase_rate
);