USE ROLE SECURITYADMIN;

CREATE USER IF NOT EXISTS RETAILROCKET_AI_APP
    TYPE = SERVICE
    DEFAULT_ROLE = RETAILROCKET_REPORTER
    DEFAULT_WAREHOUSE = RETAILROCKET_WH
    COMMENT = 'Service user for the Retailrocket Streamlit AI assistant';

GRANT ROLE RETAILROCKET_REPORTER
    TO USER RETAILROCKET_AI_APP;

ALTER USER RETAILROCKET_AI_APP
    SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqAidJMUE6Ufv0FrcuBuK
+a/ZZcaFTfoOZv//W+0NcwXkS22tehAgZf5w8pU7VFEP5+IxGy1o4qmijUQhEUm5
lWkPyDMnYRXTuYwUJ8pnwJNXevBgDCNrple9B9HUbcXGoqad+wiohGJjoT5pKEHD
FYIe3ChZkjaJYrSfz49mutO+Fz4KPoINofJwlLH8nGOsdLrP+wFc1fvuwGdRi4HA
770y7IdNu6zG15CRKlAwsF7FFaoQHIHf2PACd1Dv/+oZAyV0ZjBPhLI+uIYkyRRM
bpajC2PBCzCfT0140TPlajJdl3VCfVUiFG+hrUShK/li9q4IL89Mcw8UKLB9/X7L
aQIDAQAB';

SHOW GRANTS TO USER RETAILROCKET_AI_APP;