USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS RETAILROCKET_REPORTER;

GRANT USAGE ON WAREHOUSE RETAILROCKET_WH
    TO ROLE RETAILROCKET_REPORTER;

GRANT USAGE ON DATABASE RETAILROCKET
    TO ROLE RETAILROCKET_REPORTER;

GRANT USAGE ON SCHEMA RETAILROCKET.ANALYTICS
    TO ROLE RETAILROCKET_REPORTER;

GRANT SELECT ON ALL TABLES IN SCHEMA RETAILROCKET.ANALYTICS
    TO ROLE RETAILROCKET_REPORTER;

GRANT SELECT ON ALL VIEWS IN SCHEMA RETAILROCKET.ANALYTICS
    TO ROLE RETAILROCKET_REPORTER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAILROCKET.ANALYTICS
    TO ROLE RETAILROCKET_REPORTER;

GRANT SELECT ON FUTURE VIEWS IN SCHEMA RETAILROCKET.ANALYTICS
    TO ROLE RETAILROCKET_REPORTER;

GRANT ROLE RETAILROCKET_REPORTER TO ROLE SYSADMIN;

GRANT ROLE RETAILROCKET_REPORTER
    TO USER VISHALMURLIKUMAR;

-- Verify access using only the reporting role.
USE ROLE RETAILROCKET_REPORTER;
USE SECONDARY ROLES NONE;
USE WAREHOUSE RETAILROCKET_WH;

SELECT CURRENT_ROLE();

SELECT COUNT(*) AS TOTAL_ORDERS
FROM RETAILROCKET.ANALYTICS.FCT_ORDERS;